### PR TITLE
fix:  mFooterLocked always true in some case #716

### PR DESCRIPTION
**Pull request by lixi0912**

### CODE REVIEW

**Comment by scwang90** [comment]
The wrong way, the problem has been solved.

**Comment by scwang90** [comment]
The wrong way, the problem has been solved.

**Comment by geekDavid** [comment]
Sleep ok?




| |
wslwno1
|
|
邮箱：wslwno1@163.com
|

Signature is customized by Netease Mail Master

On 12/07/2018 00:42, 树朾 wrote:

The wrong way, the problem has been solved.

**Comment by lixi0912** [comment]
In my case, LoadStatePresenter will replace SmartRefreshLayout with LoadStateLayout and then cannot reset mFooterLocked because onDetachedFromWindow is called.

**Pull request closed without merging**
